name: lib_ui
description: ui库
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # 限制函数的连续执行，防止按钮重复点击用的 https://github.com/mhrst/just_throttle_it
  just_throttle_it: ^2.1.0
  # 用于处理IOS、Android、web三个平台的SVG资源 https://github.com/peiffer-innovations/websafe_svg
  websafe_svg: ^2.1.0
  # 动画 https://github.com/flutter/packages/tree/master/packages/animations
  animations: ^2.0.2
  # 矢量动画库：
  # pub.dev: https://pub.dev/packages/rive
  # OfficialWeb: https://rive.app/
  rive: ^0.8.1
  # 缓存网络图像文件 https://github.com/Baseflow/flutter_cached_network_image
  cached_network_image: ^3.2.0
  # 采用外接纹理的实现图片显示 https://github.com/BuildAndRelease/flutter_image_view
  flutter_image_view:
    git:
      url: https://github.com/FBSocial/flutter_image_view.git
      ref: 2.0.1+1
  # 土司 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.1.5
  # IOS原生文本输入框插件 https://gitee.com/fanbook/native_text_field
  native_text_field:
    git:
      url: https://github.com/FBSocial/native_text_field.git
      ref: 2.0.3

  lib_base:
    path: ../lib_base
  lib_theme:
    path: ../lib_theme
  lib_extension:
    path: ../lib_extension
  lib_image:
    path: ../lib_image
  lib_utils:
    path: ../lib_utils
  service:
    path: ../../module/module_service
  flutter_svg: ^1.0.3
  sliding_sheet:
    git:
      url: https://github.com/FBSocial/sliding_sheet.git
      ref: 0.5.2+2
  video_player: ^2.5.1
  simple_shadow: ^0.3.1
  device_info_plus: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  flutter_quill:
    git:
      url: https://github.com/FBSocial/fb_flutter_quill.git
      ref: e5c7ffb7d68ee5c6fede13e43b541acd4b6528d6
  device_info_plus: ^4.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

  assets:
     - assets/svg/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
