// DO NOT EDIT.
// This file is generated by **figma_tokens_to_class**, please do not edit manually.

import 'package:flutter/material.dart';
import 'package:lib_ui/src/theme/themes.dart';

class AppTheme extends InheritedWidget {
  final AppThemeData theme;
  final AppThemeData? darkTheme;

  const AppTheme({
    Key? key,
    required this.theme,
    this.darkTheme,
    required Widget child,
  }) : super(
          key: key,
          child: child,
        );

  static AppThemeData of(BuildContext context) {
    final appTheme = context.dependOnInheritedWidgetOfExactType<AppTheme>()!;
    return WidgetsBinding.instance!.window.platformBrightness == Brightness.dark
        ? appTheme.darkTheme ?? appTheme.theme
        : appTheme.theme;
  }

  @override
  bool updateShouldNotify(covariant AppTheme oldWidget) {
    return oldWidget.theme != theme || oldWidget.darkTheme != darkTheme;
  }
}
