// DO NOT EDIT.
// This file is generated by **figma_tokens_to_class**, please do not edit manually.

import 'package:flutter/material.dart';

class AppThemeData {
    final Bg bg;
    final Fg fg;
    final Other other;
    final String pingFang;
    final Medium medium;
    final Radius radius;
    final Regular regular;
    final Weight weight;

    AppThemeData({
        required this.bg,
        required this.fg,
        required this.other,
        required this.pingFang,
        required this.medium,
        required this.radius,
        required this.regular,
        required this.weight,
    });

    factory AppThemeData.light() {
        return AppThemeData(
            bg: Bg(
                one: const Color(0xfff3f4f5),
                two: const Color(0xffffffff),
            ),
            fg: Fg(
                brand: FgBrand(
                    one: const Color(0xff198cfe),
                    three: const Color(0x1a198cfe),
                    two: const Color(0x66198cfe),
                ),
                green: FgGreen(
                    one: const Color(0xff00bf7f),
                    three: const Color(0x1a00bf7f),
                    two: const Color(0x6600bf7f),
                ),
                grey: FgGrey(
                    five: const Color(0x331a2033),
                    four: const Color(0x661a2033),
                    one: const Color(0xff1a2033),
                    seven: const Color(0x0d1a2033),
                    six: const Color(0x141a2033),
                    three: const Color(0x991a2033),
                    two: const Color(0xe61a2033),
                ),
                red: FgRed(
                    one: const Color(0xfff2494a),
                    three: const Color(0x1af2494a),
                    two: const Color(0x66f2494a),
                ),
                whiteBlack: FgWhiteBlack(
                    one: const Color(0xffffffff),
                    three: const Color(0x1affffff),
                    two: const Color(0x99ffffff),
                ),
                yellow: FgYellow(
                    one: const Color(0xffffb726),
                    three: const Color(0x1affb726),
                    two: const Color(0x66ffb726),
                ),
            ),
            other: Other(
                transparent: const Color(0x00ffffff),
            ),
            pingFang: "PingFang SC",
            medium: Medium(
                f1: const TextStyle(fontSize: 14,height: 20,fontWeight: FontWeight.w500,),
                f2: const TextStyle(fontSize: 12,height: 17,fontWeight: FontWeight.w500,),
                h1: const TextStyle(fontSize: 22,height: 30,fontWeight: FontWeight.w500,),
                h2: const TextStyle(fontSize: 20,height: 28,fontWeight: FontWeight.w500,),
                h3: const TextStyle(fontSize: 17,height: 24,fontWeight: FontWeight.w500,),
                t1: const TextStyle(fontSize: 16,height: 22,fontWeight: FontWeight.w500,),
                t2: const TextStyle(fontSize: 15,height: 20,fontWeight: FontWeight.w500,),
            ),
            radius: Radius(
                five: BorderRadius.circular(10),
                four: BorderRadius.circular(9),
                one: BorderRadius.circular(4),
                seven: BorderRadius.circular(13),
                six: BorderRadius.circular(11),
                three: BorderRadius.circular(8),
                two: BorderRadius.circular(6),
            ),
            regular: Regular(
                f1: const TextStyle(fontSize: 14,height: 20,fontWeight: FontWeight.w400,),
                f2: const TextStyle(fontSize: 12,height: 17,fontWeight: FontWeight.w400,),
                h1: const TextStyle(fontSize: 22,height: 30,fontWeight: FontWeight.w400,),
                h2: const TextStyle(fontSize: 20,height: 28,fontWeight: FontWeight.w400,),
                h3: const TextStyle(fontSize: 17,height: 24,fontWeight: FontWeight.w400,),
                t1: const TextStyle(fontSize: 16,height: 22,fontWeight: FontWeight.w400,),
                t2: const TextStyle(fontSize: 15,height: 21,fontWeight: FontWeight.w400,),
            ),
            weight: Weight(
                medium: FontWeight.w500,
                regular: FontWeight.w400,
            ),
        );
    }
    factory AppThemeData.dark() {
        return AppThemeData(
            bg: Bg(
                one: const Color(0xff000000),
                two: const Color(0xff1f1f1f),
            ),
            fg: Fg(
                brand: FgBrand(
                    one: const Color(0xff1a7cdd),
                    three: const Color(0x1a1a7cdd),
                    two: const Color(0x661a7cdd),
                ),
                green: FgGreen(
                    one: const Color(0xff05a771),
                    three: const Color(0x1a05a771),
                    two: const Color(0x6605a771),
                ),
                grey: FgGrey(
                    five: const Color(0x66ffffff),
                    four: const Color(0x99ffffff),
                    one: const Color(0xe6ffffff),
                    seven: const Color(0x0dffffff),
                    six: const Color(0x14ffffff),
                    three: const Color(0xb3ffffff),
                    two: const Color(0xccffffff),
                ),
                red: FgRed(
                    one: const Color(0xffd24344),
                    three: const Color(0x1ad24344),
                    two: const Color(0x66d24344),
                ),
                whiteBlack: FgWhiteBlack(
                    one: const Color(0xff000000),
                    three: const Color(0x1a000000),
                    two: const Color(0x99000000),
                ),
                yellow: FgYellow(
                    one: const Color(0xffdc9f23),
                    three: const Color(0x1adc9f23),
                    two: const Color(0x66dc9f23),
                ),
            ),
            other: Other(
                transparent: const Color(0x00ffffff),
            ),
            pingFang: "PingFang SC",
            medium: Medium(
                f1: const TextStyle(fontSize: 14,height: 20,fontWeight: FontWeight.w500,),
                f2: const TextStyle(fontSize: 12,height: 17,fontWeight: FontWeight.w500,),
                h1: const TextStyle(fontSize: 22,height: 30,fontWeight: FontWeight.w500,),
                h2: const TextStyle(fontSize: 20,height: 28,fontWeight: FontWeight.w500,),
                h3: const TextStyle(fontSize: 17,height: 24,fontWeight: FontWeight.w500,),
                t1: const TextStyle(fontSize: 16,height: 22,fontWeight: FontWeight.w500,),
                t2: const TextStyle(fontSize: 15,height: 20,fontWeight: FontWeight.w500,),
            ),
            radius: Radius(
                five: BorderRadius.circular(10),
                four: BorderRadius.circular(9),
                one: BorderRadius.circular(4),
                seven: BorderRadius.circular(13),
                six: BorderRadius.circular(11),
                three: BorderRadius.circular(8),
                two: BorderRadius.circular(6),
            ),
            regular: Regular(
                f1: const TextStyle(fontSize: 14,height: 20,fontWeight: FontWeight.w400,),
                f2: const TextStyle(fontSize: 12,height: 17,fontWeight: FontWeight.w400,),
                h1: const TextStyle(fontSize: 22,height: 30,fontWeight: FontWeight.w400,),
                h2: const TextStyle(fontSize: 20,height: 28,fontWeight: FontWeight.w400,),
                h3: const TextStyle(fontSize: 17,height: 24,fontWeight: FontWeight.w400,),
                t1: const TextStyle(fontSize: 16,height: 22,fontWeight: FontWeight.w400,),
                t2: const TextStyle(fontSize: 15,height: 21,fontWeight: FontWeight.w400,),
            ),
            weight: Weight(
                medium: FontWeight.w500,
                regular: FontWeight.w400,
            ),
        );
    }

}

class Weight {
    final FontWeight medium;
    final FontWeight regular;

    Weight({
        required this.medium,
        required this.regular,
    });
}

class Regular {
    final TextStyle f1;
    final TextStyle f2;
    final TextStyle h1;
    final TextStyle h2;
    final TextStyle h3;
    final TextStyle t1;
    final TextStyle t2;

    Regular({
        required this.f1,
        required this.f2,
        required this.h1,
        required this.h2,
        required this.h3,
        required this.t1,
        required this.t2,
    });
}

class Radius {
    final BorderRadius five;
    final BorderRadius four;
    final BorderRadius one;
    final BorderRadius seven;
    final BorderRadius six;
    final BorderRadius three;
    final BorderRadius two;

    Radius({
        required this.five,
        required this.four,
        required this.one,
        required this.seven,
        required this.six,
        required this.three,
        required this.two,
    });
}

class Medium {
    final TextStyle f1;
    final TextStyle f2;
    final TextStyle h1;
    final TextStyle h2;
    final TextStyle h3;
    final TextStyle t1;
    final TextStyle t2;

    Medium({
        required this.f1,
        required this.f2,
        required this.h1,
        required this.h2,
        required this.h3,
        required this.t1,
        required this.t2,
    });
}

class Other {
    final Color transparent;

    Other({
        required this.transparent,
    });
}

class Fg {
    final FgBrand brand;
    final FgGreen green;
    final FgGrey grey;
    final FgRed red;
    final FgWhiteBlack whiteBlack;
    final FgYellow yellow;

    Fg({
        required this.brand,
        required this.green,
        required this.grey,
        required this.red,
        required this.whiteBlack,
        required this.yellow,
    });
}

class FgYellow {
    final Color one;
    final Color three;
    final Color two;

    FgYellow({
        required this.one,
        required this.three,
        required this.two,
    });
}

class FgWhiteBlack {
    final Color one;
    final Color three;
    final Color two;

    FgWhiteBlack({
        required this.one,
        required this.three,
        required this.two,
    });
}

class FgRed {
    final Color one;
    final Color three;
    final Color two;

    FgRed({
        required this.one,
        required this.three,
        required this.two,
    });
}

class FgGrey {
    final Color five;
    final Color four;
    final Color one;
    final Color seven;
    final Color six;
    final Color three;
    final Color two;

    FgGrey({
        required this.five,
        required this.four,
        required this.one,
        required this.seven,
        required this.six,
        required this.three,
        required this.two,
    });
}

class FgGreen {
    final Color one;
    final Color three;
    final Color two;

    FgGreen({
        required this.one,
        required this.three,
        required this.two,
    });
}

class FgBrand {
    final Color one;
    final Color three;
    final Color two;

    FgBrand({
        required this.one,
        required this.three,
        required this.two,
    });
}

class Bg {
    final Color one;
    final Color two;

    Bg({
        required this.one,
        required this.two,
    });
}

